### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by pepski1270** [BryceCanyonCounty/bcc-loadscreen#4]
i tried this script with the helper. nothing happens. it's running though

**Comment by uwuanangel** [comment]
You have to ensure the helper before the loadscreen and make sure its at the top of your resources.cfg

**Comment by uwuanangel** [comment]
> i tried this script with the helper. nothing happens. it's running though
You have to ensure the helper before the loadscreen and make sure its at the top of your resources.cfg

**Comment by pepski1270** [comment]
> > i tried this script with the helper. nothing happens. it's running though
> > You have to ensure the helper before the loadscreen and make sure its at the top of your resources.cfg

![image](https://user-images.githubusercontent.com/104223970/215750996-09d56b48-0984-4a6f-a58d-b4e3b041c529.png)
still got no luck

**Comment by DavFount** [comment]
Do you have any errors in the f8 or server console?

**Comment by pepski1270** [comment]
> Do you have any errors in the f8 or server console?

no errors sir

**Comment by AndrewR3K** [comment]
did you make any changes to the config or anything?

**Comment by pepski1270** [comment]
> did you make any changes to the config or anything?

i just replace the png file

**Comment by AndrewR3K** [comment]
Can you try with the default png and ensure it works as-is.

if it works then your png is most likely too bug of a file for cfx. To resolve I believe you would need to downscale the image

**Comment by pepski1270** [comment]
> Can you try with the default png and ensure it works as-is.
> 
> if it works then your png is most likely too bug of a file for cfx. To resolve I believe you would need to downscale the image

i got to reupload the file and the png, downscale a little bit and it works now. thanks!
