### ISSUE TITLE
Satchel for RedM changes to  Undefined

### ISSUE THREAD

**Issue by ghost** [BryceCanyonCounty/bcc-loadscreen#5]
I was facing issues with my inventory in my satchel for the longest time saying undefined. today i went over every script to see which one was causing the issues with the satchel and found out it had to do with the bcc-loading screen. I'm not sure if it has to do with the photo i am using on the load up screen or not. but if any help or ideas why this would make my in game satchel be set to undefined?

https://cdn.discordapp.com/attachments/1076722086682296324/1078785140945326102/image.png

**Comment by AndrewR3K** [comment]
There is no overlap with vorp inventory, and I have not seen this ever. So strange! 

If you can send what you are using for the background that may help me reproduce this issue. 

Thanks!

**Comment by ghost** [comment]
Here is my stuff

https://drive.google.com/file/d/1QpeyOyC_-oGss0p-WwXVJSruZvT0kO0I/view?usp=drivesdk

**Comment by AndrewR3K** [comment]
And just to ensure I produce the same results, can you send me what your config looks like?

My apoIogies on the delay,  will be testing this today/tomorrow.

**Comment by AndrewR3K** [comment]
Ah, disregard my last message. I see you sent the whole thing. I will test soon and see if this happens for me.

**Comment by ghost** [comment]
I uploaded to my Google drive and sent you what I have so far with the
picture i was using. I had a video. But it would freeze at the end so i
stopped using video. Unless i upload the video to YouTube and put the link
in the config might work. But the config and files are all in the drive i
shared

https://drive.google.com/file/d/1QpeyOyC_-oGss0p-WwXVJSruZvT0kO0I/view?usp=drivesdk

**Comment by ghost** [comment]
Okay let me know. Thank you

**Comment by AndrewR3K** [comment]
One thing to try, just off the top of my head.

CFX has a file limit on scripts. So the image/video might be too large or just close enough to cause issues. 

I would try with a different image, and/or with a downscaled image. 

I will still test, but just some things to try in the meantime.

**Comment by ghost** [comment]
I can definitely try a smaller image or maybe use video from YouTube like I
provide right?
