### ISSUE TITLE
Loadscreen blocked

### ISSUE THREAD

**Issue by d1Nca** [BryceCanyonCounty/bcc-loadscreen#6]
hello guys, i install this resourse for my server but the game starts and loadscreen stuck on loading....

**Comment by AndrewR3K** [comment]
Please make sure to install the helper scripts as well. [bcc-loadscreen-helper](https://github.com/BryceCanyonCounty/bcc-loadscreen-helper)

full installation instruction can be found here: https://github.com/BryceCanyonCounty/bcc-loadscreen?tab=readme-ov-file#install
